<?php
$location_array=array(

'Allorallen' => array(57,59,20,1,1,1,1,0),
'Miereallen' => array(47,85,20,1,1,1,1,0),
'Mainelle' => array(53,106,20,1,1,1,1,0),
'Barashta' => array(103,142,20,1,1,1,1,0),
'Dorelle Caromon' => array(139,147,20,1,1,1,1,0),
'Tear' => array(167,132,20,1,1,1,1,0),
'Stedding Shangtai' => array(198,114,0,0,0,0,0,0),
'Al-ap-cair-ap-rahienallen' => array(174,73,20,1,1,1,1,0),
'Tar Valon' => array(163,59,20,1,1,1,1,0),
'Hai Caemlyn' => array(152,94,20,1,1,1,1,0),
'Aren Mador' => array(154,112,20,1,1,1,1,0),
'Shanaine' => array(96,101,20,1,1,1,1,0),
'Manetheren' => array(89,90,20,1,1,1,1,0),
'Iman' => array(84,73,20,1,1,1,1,0),
'Deranbar' => array(117,30,20,1,1,1,1,0),


'The Jaramide Coast' => array(93,30,0,0,0,0,0,0),
'The Safer Mountains' => array(85,66,0,0,0,0,0,0),
'The Safer Crossroads' => array(68,73,0,0,0,0,0,0),
'The Jaramide Plains' => array(68,59,0,0,0,0,0,0),
'Outer Allorallen' => array(62,59,0,0,0,0,0,0),
'The Safer Coast' => array(58,73,0,0,0,0,0,0),
'The Manetheren Border' => array(83,90,0,0,0,0,0,0),
'The Misty Mountains' => array(92,90,0,0,0,0,0,0),
'Outer Mainelle' => array(59,105,0,0,0,0,0,0),
'The Safer Border' => array(82,103,0,0,0,0,0,0),
'The Manetheren Crossroads' => array(110,104,0,0,0,0,0,0),
'Southern Eharon' => array(104,136,0,0,0,0,0,0),
'The Essenia Highlands' => array(158,113,0,0,0,0,0,0),
'The Essenia River Crossing' => array(168,125,0,0,0,0,0,0),
'Southern Tar Valon' => array(163,73,0,0,0,0,0,0),
'Central Coremanda' => array(151,72,0,0,0,0,0,0),
'Northern Tar Valon' => array(163,53,0,0,0,0,0,0),
'The Essenia Crossroads' => array(170,113,0,0,0,0,0,0),
'The Waste' => array(212,114,0,0,0,0,0,0),
'The Blight Border' => array(212,20,0,0,0,0,0,0),
'The Blasted Lands' => array(163,10,0,0,0,0,0,0),
'The Blight' => array(118,16,0,0,0,0,0,0),

'The Jaramide Forest' => array(107,30,10,0,1,1,0,1),
'The West Jaramide Forest' => array(62,57,10,0,1,1,0,1),
'The Safer Forest' => array(53,79,10,0,1,1,0,1),
'The Essenia Forest' => array(158,116,10,0,1,1,0,1),
'The Coremanda Forest' => array(164,94,10,0,1,1,0,1),
'The Tar Valon Woods' => array(166,53,10,0,1,1,0,1),

'The Safer Mines' => array(89,67,10,0,1,1,0,3),
'The Manetheren Mines' => array(92,83,10,0,1,1,0,3),
'The Aelgar Mines' => array(96,113,10,0,1,1,0,3),
'The Almoren Mines' => array(174,62,10,0,1,1,0,3),
'The West Essenia Mines' => array(198,102,10,0,1,1,0,3),

'The Alegar Hunting Grounds' => array(59,110,10,0,1,1,0,2),
'The Eharon Hunting Grounds' => array(109,137,10,0,1,1,0,2),
'The Coastal Hunting Grounds' => array(143,138,10,0,1,1,0,2),
'The Essenia Hunting Grounds' => array(172,125,10,0,1,1,0,2),


);

// '' => array(,,,,,,,),
// array( x , y , max_resource_cost , has_market, has_trading_post, has_bank, has_armory, has_resource)
// woodcutting 1, hunting 2, mining 3
?>
